CREATE TABLE USERS (
    ID_US INTEGER NOT NULL,
    NAME_US VARCHAR(255),
    EMAIL_US VARCHAR(255),
    PASSW VARCHAR(255),
    CONSTRAINT PK_USERS PRIMARY KEY (ID_US),
    CONSTRAINT UQ_USERS_1 UNIQUE (NAME_US)
);
