CREATE TABLE TASKS (
    ID_TASK INTEGER NOT NULL,
    NAME_TASK VARCHAR(255),
    TEXT_TASK VARCHAR(500),
    DETHLINE_TASK TIMESTAMP,
    CREATED_TASK TIMESTAMP,
    STATUS_TASK VARCHAR(3),
    EXEC_TASK BOOLEAN,
    LAST_CORRECT_TASK TIMESTAMP,
    ASSIGNED_TASK INTEGER,
    DEPENDENCIES_TASK VARCHAR(11) CHARACTER SET NONE,
    CONSTRAINT FK_TASKS_1 FOREIGN KEY (ASSIGNED_TASK) REFERENCES USERS (ID_US),
    CONSTRAINT PK_TASKS PRIMARY KEY (ID_TASK)
);
