SET TERM ^;
CREATE OR ALTER TRIGGER TASKS_BI
  FOR TASKS BEFORE INSERT
AS BEGIN END^

SET TERM ;^

SET TERM ^;
CREATE OR ALTER TRIGGER USERS_BI
  FOR USERS BEFORE INSERT
AS BEGIN END^

SET TERM ;^

SET TERM ^;
CREATE OR ALTER TRIGGER TASKS_BI FOR TASKS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.ID_TASK IS NULL) THEN
NEW.ID_TASK = GEN_ID(SEQ_TASKS_ID_TASK,1);
END^
SET TERM ;^

SET TERM ^;
CREATE OR ALTER TRIGGER USERS_BI FOR USERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.ID_US IS NULL) THEN
NEW.ID_US = GEN_ID(SEQ_USERS_ID_US,1);
END^
SET TERM ;^
